### ISSUE TITLE
error Found incompatible module

### ISSUE THREAD

**Issue by sparkydman** [ucontex/ucontex-client#7]
## I keep having this error each time i try to deploy on netlify. Please any idea why this error?

3:09:53 PM: > GPG signature looks good
3:09:53 PM: > Extracting to ~/.yarn...
3:09:53 PM: > Adding to $PATH...
3:09:53 PM: > Successfully installed Yarn 1.17.0! Please open another terminal where the `yarn` command will now be available.
3:09:54 PM: Installing NPM modules using Yarn version 1.17.0
3:09:55 PM: yarn install v1.17.0
3:09:55 PM: [1/5] Validating package.json...
3:09:55 PM: error nextjs-custom@1.0.0: The engine "node" is incompatible with this module. Expected version "^12.13.0". Got "10.20.1"
3:09:55 PM: error nextjs-custom@1.0.0: The engine "yarn" is incompatible with this module. Expected version "^1.22.4". Got "1.17.0"
3:09:55 PM: error Found incompatible module.
3:09:55 PM: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
3:09:55 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
3:09:55 PM: Error during Yarn install
3:09:55 PM: Error running command: Build script returned non-zero exit code: 1
3:09:55 PM: Shutting down logging, 2 messages pending # #6

**Comment by joshikeno** [comment]
@sparkydman Thanks for your efforts here. We concluded to use [now deployment](https://zeit.co/docs) and also stick with the `node package manager` for this project
